// Shorts-only per-letter extras, on top of src/data/letters.ts.
//
// WHY THIS FILE EXISTS: every app clip in public/audio/letters/ ends with a short
// EXAMPLE PHRASE after "<Letter> for <Word>" — e.g. A's clip is
//   "A says Aaa Aaa Aaa.  A for Ant.  A tiny ant walks fast."
// The 16:9 A→Z video never staged that tail, so it was never written down. In a
// 25-second Short it's ~15% of the runtime, and a static card over it would be an
// instant reject — so each phrase gets its own beat, and needs its text + start.
//
// Word times are MEASURED, not guessed — forced-aligned against the real clip:
//   cd tools && ./.venv/bin/python align_audio.py \
//       ../public/audio/letters/a_ant_sound.mp3 scripts/a_ant_sound.txt
// which writes <name>.phrases.json / .words.json / .srt next to the audio.
// Scripts live in tools/scripts/<audio-stem>.txt. Re-run per letter to fill B–Z.
//
// Gotcha found while doing A: several clips have a non-word giggle between the
// word and the phrase ("Hee hee" at 4.96–5.06 in A's). Keep it in the alignment
// script so the timings stay honest, but don't put it on screen.

export interface PhraseWord {
  w: string; // display text
  at: number; // seconds into the clip when it is spoken
}

export interface LetterShortExtra {
  words: PhraseWord[]; // the example phrase, word by word
}

import letterPhrases from "./letterPhrases.json";

// All 26, generated by tools/build_letter_phrases.py — do not hand-edit.
// To change wording, edit the reviewed text in tools/scripts/tails.json and re-run.
export const LETTER_SHORT_EXTRAS = letterPhrases as Record<string, LetterShortExtra>;

// The phrase row should open a beat BEFORE the first word, so the words light up
// into a row that is already there rather than arriving with it.
export const phraseStartOf = (e: LetterShortExtra) => Math.max(0, e.words[0].at - 0.35);

// A→B … Z→A, so the series loops.
export const nextLetterOf = (letter: string): string => {
  const i = letter.toUpperCase().charCodeAt(0) - 65;
  return String.fromCharCode(65 + ((i + 1) % 26));
};

// ── Shared framing lines ─────────────────────────────────────────────────────
// Recorded ONCE and reused by all 26 episodes — this is what keeps the series at
// zero new per-letter recording. `null` = not recorded yet; the beat still renders
// (music + SFX only) and the voice drops in later with no layout change.
export interface SharedLine {
  src: string | null; // path under public/
  dur: number; // seconds (ffprobe) — 0 while unrecorded
}

// Recorded once, reused by all 26 episodes. ALL shared framing lines live in
// public/audio/common/ — per-letter content lives elsewhere (letters/, words/).
export const SHARED: Record<"yourTurn" | "cta", SharedLine> = {
  yourTurn: { src: "audio/common/now_its_your_turn.mp3", dur: 1.881 }, // "Now it's your turn!"
  cta: { src: null, dur: 0 }, // "A new letter every day — follow so you don't miss tomorrow's!"
};

// ── praise after the child answers ───────────────────────────────────────────
// Seven takes so a viewer bingeing the series doesn't hear one line 26 times.
// 7 into 26 means consecutive letters always differ. Durations measured from the
// recordings in public/audio/common/ (they are shorter than the app's old
// practice-round takes, so the beat length differs per letter).
export const PRAISE_POOL: { src: string; text: string; dur: number }[] = [
  { src: "audio/common/yes_thats_right.mp3", text: "That's right!", dur: 0.83 },
  { src: "audio/common/great_job.mp3", text: "Great job!", dur: 1.0 },
  { src: "audio/common/perfect.mp3", text: "Perfect!", dur: 0.65 },
  { src: "audio/common/superstar.mp3", text: "Superstar!", dur: 1.2 },
  { src: "audio/common/well_done.mp3", text: "Well done!", dur: 1.07 },
  { src: "audio/common/woohoo.mp3", text: "Woohoo!", dur: 0.84 },
  { src: "audio/common/you_got_it.mp3", text: "You got it!", dur: 1.02 },
];

export const praiseFor = (letter: string) =>
  PRAISE_POOL[(letter.toUpperCase().charCodeAt(0) - 65) % PRAISE_POOL.length];

// ── Z's finale narration ─────────────────────────────────────────────────────
// Four separate takes rather than one long line, so each lands on the beat it
// describes: the completion headline, then the store search, then the download,
// then the badges. Total 11.53s.
export const Z_FINALE: { src: string; dur: number }[] = [
  { src: "audio/common/z1_wow.mp3", dur: 4.35 },           // "Wow — you know all 26 letters, A to Z"
  { src: "audio/common/z2_keep_learning.mp3", dur: 1.85 }, // "Now let's keep learning together"
  { src: "audio/common/z3_find_app.mp3", dur: 3.74 },      // "Find Kids English Learning on the App Store or Google Play"
  { src: "audio/common/z4_free.mp3", dur: 1.588 },         // "It's completely free!"
];

// ── "More · <letter> · words" ────────────────────────────────────────────────
// Spoken as three clips rather than one recording, so ONE pair of takes covers
// all 26 episodes: "More" and "words" are recorded once, and the letter name in
// the middle is the app's own existing clip.
//   public/audio/more.mp3 + public/audio/letter_names/letter_<x>.mp3 + words.mp3
// Letter-name durations are already measured as `d0` in src/data/recognition.ts,
// so there is nothing new to hardcode. (tools/prep_letter_names.sh)
export const SPOKEN_MORE: SharedLine = { src: "audio/common/more.mp3", dur: 0.44 };
export const SPOKEN_WORDS: SharedLine = { src: "audio/common/words.mp3", dur: 0.716 };
export const WORD_GAP = 0.06; // breath between the three clips
export const letterNameSrc = (letter: string) => `audio/letter_names/letter_${letter.toLowerCase()}.mp3`;
