// ── The audio mix, in one place ─────────────────────────────────────────────
//
// Every lesson reel reads its bed level from here, so a music-free master is ONE edit
// rather than three, and no part can drift to a different level than its siblings.
//
//   MUSIC_BED = 0     -> a clean, teacher-only render (the reel still renders; the bed
//                        simply plays at zero, so nothing else has to change)
//   MUSIC_BED = 0.055 -> the shipped level: audible in the gaps, never over the voice
//
// The bed itself is public/music_bed.mp3, generated by tools/make_music.py — a blooming
// pentatonic with no attack. It is self-synthesised, so it cannot trip a copyright
// fingerprint on any platform.
export const MUSIC_BED = 0.055;

/** fade shape, in frames, shared by every lesson */
export const MUSIC_FADE_IN = 40;
export const MUSIC_FADE_OUT = 70;
